spring:
  application:
    name: SpringBootJdbc
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Rkakrnl1!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8089
